// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Описание API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.0
 */

package openapi




type SignInput struct {

	// Данные в base64
	Message string `json:"message"`

	// cryptopro - для работы с провайдером КриптоПРО   avest - для работы с провайдером Avest 
	Provider string `json:"provider"`
}

// AssertSignInputRequired checks if the required fields are not zero-ed
func AssertSignInputRequired(obj SignInput) error {
	elements := map[string]interface{}{
		"message": obj.Message,
		"provider": obj.Provider,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSignInputConstraints checks if the values respects the defined constraints
func AssertSignInputConstraints(obj SignInput) error {
	return nil
}
