// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Описание API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.0
 */

package openapi




type InvalidData struct {

	// Статус
	Status string `json:"status,omitempty"`

	// Ошибка
	Error string `json:"error,omitempty"`
}

// AssertInvalidDataRequired checks if the required fields are not zero-ed
func AssertInvalidDataRequired(obj InvalidData) error {
	return nil
}

// AssertInvalidDataConstraints checks if the values respects the defined constraints
func AssertInvalidDataConstraints(obj InvalidData) error {
	return nil
}
