// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Описание API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.0
 */

package openapi




type SignOutput struct {

	// Статус выполнения
	Status string `json:"status,omitempty"`

	// Выработанная подпись
	Sign string `json:"sign,omitempty"`
}

// AssertSignOutputRequired checks if the required fields are not zero-ed
func AssertSignOutputRequired(obj SignOutput) error {
	return nil
}

// AssertSignOutputConstraints checks if the values respects the defined constraints
func AssertSignOutputConstraints(obj SignOutput) error {
	return nil
}
